stages:
  - build
  - test
  - dockertest

# Common scripts
.common_scripts:
  npm_shared:
    - cd shared
    - npm install
    - cd ../
  npm_auth_ms:
    - cd auth-ms
    - npm install
  npm_listing_ms:
    - cd listing-ms
    - npm install
  npm_bid_ms:
    - cd bid-ms
    - npm install

# Templates
.build_template:
  image: node:iron-alpine
  stage: build
  before_script:
    - cd shared
    - npm install
    - cd ../

.test_template:
  image: node:iron-alpine
  services:
    - name: mongodb/mongodb-community-server:latest
      alias: mongo-integration
  stage: test
  before_script:
    - !reference [.common_scripts, npm_shared]

# Build
build-auth-ms:
  extends: .build_template
  script:
    - !reference [.common_scripts, npm_auth_ms]
    - npm run build

build-listing-ms:
  extends: .build_template
  script:
    - !reference [.common_scripts, npm_listing_ms]
    - npm run build

build-bid-ms:
  extends: .build_template
  script:
    - !reference [.common_scripts, npm_bid_ms]
    - npm run build

# Test
test-auth-ms:
  extends: .test_template
  variables:
    DB_CON_STRING: "mongodb://mongo-integration:27017/integration-bikehut-users"
  script:
    - !reference [.common_scripts, npm_auth_ms]
    - cp dotenv.local.example .env.test
    - npm run test

dockertest:
  stage: dockertest
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  variables:
    # connect to the docker daemon inside of the job container (docker-in-docker)
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker -v
    - docker build -t my-docker-image .
