stages:
    - test
    - dockertest

test: 
    image: node:iron-alpine
    stage: test
    script:
        - ls
        - node --version

 dockertest: 
    stage: dockertest
    image: docker:25.0.3
      services:
        - docker:25.0.3-dind
    script:
        - ls
        - docker -v

