stages:
  - build
  - dockertest

build-auth-ms:
  image: node:iron-alpine
  stage: build
  script:
    - cd auth-ms
    - npm install
    - npm run build

build-listing-ms:
  image: node:iron-alpine
  stage: build
  script:
    - cd listing-ms
    - npm install
    - npm run build

build-bid-ms:
  image: node:iron-alpine
  stage: build
  script:
    - cd bid-ms
    - npm install
    - npm run build

dockertest:
  stage: dockertest
  image: docker:25.0.3
  services:
    - docker:25.0.3-dind
  variables:
    # connect to the docker daemon inside of the job container (docker-in-docker)
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker -v
    - docker build -t my-docker-image .
