stages:
    - test
    - dockertest

test: 
    image: node:iron-alpine
    stage: test
    script:
        - ls
        - node --version

dockertest: 
    stage: dockertest
    image: docker:25.0.3
    services:
        - docker:25.0.3-dind
    variables:
    # connect to the docker daemon inside of the job container (docker-in-docker)
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ''
    script:
        - docker -v
        - docker build -t my-docker-image .

