stages:
    - test
    - dockertest

test: 
    image: node:iron-alpine
    stage: test
    script:
        - ls
        - node --version

dockertest: 
    stage: dockertest
    image: docker:25.0.3
    # services:
    #     - docker:25.0.3-dind
    script:
        - docker -v
        - docker build -t my-docker-image .
        - docker run my-docker-image

