apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: media-ms
    version: "1.0"
  name: media-ms-deployment
  namespace: househunters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-ms
  template:
    metadata:
      labels:
        app: media-ms
        version: "1.0"
    spec:
      # serviceAccountName: acua-ksa
      containers:
      - name: media-ms-container
        image: ydoykov/s6-househunters-media-ms:latest
        imagePullPolicy: Always
        env:
          - name: RABBITMQ_HOST
            value: "rabbitmq-service"
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: shared-secrets
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: shared-secrets
                key: RABBITMQ_PASSWORD
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: shared-secrets
                key: AWS_ACCESS_KEY_ID
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: shared-secrets
                key: S3_BUCKET
          - name: S3_REGION
            valueFrom:
              secretKeyRef:
                name: shared-secrets
                key: S3_REGION
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: shared-secrets
                key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 9999
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 125m
            memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-ms
  name: media-ms-service
  namespace: househunters
spec:
  ports:
    - name: http
      # Internal cluster port
      port: 9999
      # Port inside of pod
      targetPort: 9999
  selector:
    # Pods with label
    app: media-ms

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: media-ms-autoscaler
  namespace: househunters
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: media-ms-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50